const STATUS_DRAFT = 'STATUS_DRAFT';
const STATUS_TODO = 'STATUS_TODO';
const STATUS_DOING = 'STATUS_DOING';
const STATUS_DONE = 'STATUS_DONE';
const STATUS_CLOSED = 'STATUS_CLOSED';

export { STATUS_CLOSED, STATUS_DONE, STATUS_TODO, STATUS_DRAFT, STATUS_DOING };
